import Head from 'next/head';
import { Box, Text, Transition } from '@mantine/core';
import { useEffect, useState } from 'react';
import Navbar from '@/components/Header/Navbar';
import { useMediaQuery } from '@mantine/hooks';

export default function Home() {
	const desktop = useMediaQuery('(min-width:900px)');

	const [isLoading, setIsLoading] = useState(true);

	useEffect(() => {
		setTimeout(() => {
			setIsLoading(false);
		}, 500);
	}, []);
	return (
		<>
			<Head>
				<title>Viktor Mellin - About me</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box
				component='main'
				sx={{
					height: '100vh',
					margin: '0 auto',
					maxWidth: '1200px',
					display: 'flex',
					flexDirection: 'column',
					padding: desktop ? 0 : '1rem 2rem',
				}}
			>
				<Box
					component='header'
					sx={{
						height: '40%',
						display: 'flex',
						flexDirection: 'column',
						justifyContent: 'space-between',
					}}
				>
					<Navbar />
					<Box component='section'>
						<Transition mounted={!isLoading} transition='fade' duration={1000} timingFunction='ease'>
							{(styles) => (
								<Box
									style={styles}
									sx={{
										fontSize: desktop ? '1.1rem' : '1rem',
									}}
								>
									<Text
										component='h1'
										sx={{
											fontFamily: 'Source Serif Pro, serif',
											fontSize: '2.5rem',
											fontWeight: 'bold',
											marginBottom: '1rem',
										}}
									>
										About me.
									</Text>
									<Text>
										Hi, I&apos;m Viktor, 23 years old and currently live in Gotland, Sweden. I have had an interest in
										coding since high school, but it was after I realized that my university studies in business economy
										was not something I wanted to work with, that I decided to change path and focus more on my interest
										and learn more about coding. I love how I always learn something new every day working on projects,
										the process behind it with the problem solving, and the satisfaction when something finally works.
									</Text>
									<Text>
										I have always had a big interest in tech and enjoy spending my time at the computer. Playing various
										games, talking with friends, or just working on some personal projects to try and broaden my
										experience and knowledge.
									</Text>
								</Box>
							)}
						</Transition>
					</Box>
				</Box>
				<Box component='footer'></Box>
			</Box>
		</>
	);
}
