import Head from 'next/head';
import { Box, MediaQuery, Transition } from '@mantine/core';

import Header from '@/components/Header';
import { useEffect, useState } from 'react';
import Projects from '@/components/Projects';
import { useMediaQuery } from '@mantine/hooks';

export default function Home() {
	const desktop = useMediaQuery('(min-width:900px)');

	const [isLoading, setIsLoading] = useState(true);

	useEffect(() => {
		setTimeout(() => {
			setIsLoading(false);
		}, 500);
	}, []);
	return (
		<>
			<Head>
				<title>Viktor Mellin - Home</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box
				component='main'
				sx={{
					minHeight: '100vh',
					margin: '0 auto',
					maxWidth: '1200px',
					display: 'flex',
					flexDirection: 'column',
					padding: desktop ? 0 : '1rem 2rem',
				}}
			>
				<Header />
				<Transition mounted={!isLoading} transition='fade' duration={1000} timingFunction='ease'>
					{(styles) => (
						<Box
							style={styles}
							component='section'
							sx={{
								flex: '1',
								display: 'flex',
								alignItems: 'center',
							}}
						>
							<Projects />
						</Box>
					)}
				</Transition>
				<Box component='footer'></Box>
			</Box>
		</>
	);
}
